export type TransactionType = 'income' | 'expense';
export type TransactionCategory = 'Food' | 'Transport' | 'Shopping' | 'Salary' | 'Investment' | 'Health' | 'Entertainment' | 'Utilities' | 'Other';
export type PaymentMethod = 'Credit Card' | 'Bank Transfer' | 'Cash' | 'UPI' | 'Apple Pay';

export interface Transaction {
  id: string;
  type: TransactionType;
  title: string;
  merchant: string;
  description: string;
  amount: number;
  category: TransactionCategory;
  paymentMethod: PaymentMethod;
  date: string;
  notes?: string;
  receiptUrl?: string;
}

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    type: 'expense',
    title: 'Starbucks Coffee',
    merchant: 'Starbucks',
    description: 'Morning latte and croissant',
    amount: 12.50,
    category: 'Food',
    paymentMethod: 'Credit Card',
    date: '2026-07-15T08:30:00Z',
    notes: 'Meeting with client',
  },
  {
    id: '2',
    type: 'income',
    title: 'Monthly Salary',
    merchant: 'TechCorp Inc.',
    description: 'July base salary',
    amount: 8500.00,
    category: 'Salary',
    paymentMethod: 'Bank Transfer',
    date: '2026-07-01T09:00:00Z',
    notes: 'Regular monthly payout',
  },
  {
    id: '3',
    type: 'expense',
    title: 'Uber Ride',
    merchant: 'Uber',
    description: 'Ride to airport',
    amount: 45.00,
    category: 'Transport',
    paymentMethod: 'UPI',
    date: '2026-07-14T18:00:00Z',
    notes: 'Trip to JFK',
  },
  {
    id: '4',
    type: 'expense',
    title: 'Amazon Purchase',
    merchant: 'Amazon',
    description: 'Mechanical Keyboard (Keychron K2)',
    amount: 99.00,
    category: 'Shopping',
    paymentMethod: 'Credit Card',
    date: '2026-07-13T14:20:00Z',
    notes: 'Work from home upgrade',
  },
  {
    id: '5',
    type: 'income',
    title: 'Dividend Payout',
    merchant: 'Vanguard',
    description: 'Quarterly dividends from VOO',
    amount: 240.50,
    category: 'Investment',
    paymentMethod: 'Bank Transfer',
    date: '2026-07-12T10:00:00Z',
    notes: 'Passive income',
  },
  {
    id: '6',
    type: 'expense',
    title: 'Grocery Shopping',
    merchant: 'Whole Foods',
    description: 'Weekly groceries and organic produce',
    amount: 120.75,
    category: 'Food',
    paymentMethod: 'Cash',
    date: '2026-07-11T16:45:00Z',
    notes: 'Meal prep for the week',
  },
  {
    id: '7',
    type: 'expense',
    title: 'Netflix Subscription',
    merchant: 'Netflix',
    description: 'Monthly premium plan',
    amount: 19.99,
    category: 'Entertainment',
    paymentMethod: 'Credit Card',
    date: '2026-07-10T00:00:00Z',
    notes: 'Automatic renewal',
  },
  {
    id: '8',
    type: 'expense',
    title: 'Gym Membership',
    merchant: 'Equinox',
    description: 'Monthly membership fee',
    amount: 200.00,
    category: 'Health',
    paymentMethod: 'Credit Card',
    date: '2026-07-09T07:00:00Z',
    notes: 'Annual plan monthly charge',
  },
  {
    id: '9',
    type: 'income',
    title: 'Freelance Project',
    merchant: 'Client X',
    description: 'UI Design for landing page',
    amount: 1200.00,
    category: 'Other',
    paymentMethod: 'UPI',
    date: '2026-07-08T12:00:00Z',
    notes: 'Project completed ahead of schedule',
  },
  {
    id: '10',
    type: 'expense',
    title: 'Electricity Bill',
    merchant: 'ConEd',
    description: 'Monthly electricity bill',
    amount: 145.20,
    category: 'Utilities',
    paymentMethod: 'Bank Transfer',
    date: '2026-07-07T11:00:00Z',
    notes: 'Summer peak usage',
  },
  {
    id: '11',
    type: 'expense',
    title: 'Dinner at Nobu',
    merchant: 'Nobu',
    description: 'Fine dining experience',
    amount: 350.00,
    category: 'Food',
    paymentMethod: 'Credit Card',
    date: '2026-07-06T20:00:00Z',
    notes: 'Celebration dinner',
  },
  {
    id: '12',
    type: 'expense',
    title: 'Pharmacy',
    merchant: 'CVS',
    description: 'Vitamins and prescriptions',
    amount: 65.40,
    category: 'Health',
    paymentMethod: 'Cash',
    date: '2026-07-05T15:30:00Z',
    notes: 'Monthly meds',
  },
  {
    id: '13',
    type: 'income',
    title: 'Cashback Reward',
    merchant: 'Chase',
    description: 'Quarterly cashback on spending',
    amount: 85.00,
    category: 'Other',
    paymentMethod: 'Bank Transfer',
    date: '2026-07-04T09:00:00Z',
    notes: 'Cashback reward',
  },
  {
    id: '14',
    type: 'expense',
    title: 'Apple Music',
    merchant: 'Apple',
    description: 'Family plan subscription',
    amount: 16.99,
    category: 'Entertainment',
    paymentMethod: 'Credit Card',
    date: '2026-07-03T00:00:00Z',
    notes: 'Automatic renewal',
  },
  {
    id: '15',
    type: 'expense',
    title: 'Gas Station',
    merchant: 'Shell',
    description: 'Full tank of premium gas',
    amount: 72.00,
    category: 'Transport',
    paymentMethod: 'Credit Card',
    date: '2026-07-02T17:15:00Z',
    notes: 'Road trip fuel',
  },
];
